### ISSUE TITLE
RigidBody spins with a fixed joint

### ISSUE THREAD

**Issue by yepw** [dimforge/rapier.js#148]
Hi, I was trying to use fixed joints to connect 3 objects: ground (fixed rigid-body),  object1 (dynamic rigid-body), and object2 (dynamic rigid-body)
ground <---- (fixed joint) ---->  object1 <----- (fixed joint)   ---->  object2
However, only object1 is static. The position of object2 keeps changing. 
I created a fiddle. Any help is appreciated.
https://jsfiddle.net/yepwang/xv9jz6np/65/

**Comment by LeXXik** [comment]
Added some visuals to see what's happening:
https://jsfiddle.net/LeXXik/7pmufe25/4/

**Comment by sebcrozet** [comment]
Hi! The issues is the `.setAdditionalMass(1.0)`. This will reduce the solver’s convergence significantly because the rigid-body’s mass becomes much higher than its angular inertia (that creates an imbalance between the angular and linear joint error correction). There are a few possible workarounds:
- Remove `.setAdditionalMass(1.0)` altogether.
- Or, remove `.setAdditionalMass(1.0)` and increase the density of the collider (that way it will be heavier and the angular inertia will be adjusted accordingly).
- Or, add more angular inertia with `.setAdditionalPrincipalAngularInertia`, but the best value might be tricky to compute. Maybe we should change the API `.setAdditionalMass` adjusts the angular inertia accordingly.
