### ISSUE TITLE
First RigidBody always has a handle of 0 instead of unique identifier

### ISSUE THREAD

**Issue by jorjordandan** [dimforge/rapier.js#164]
I was debugging an issue with the r@eact-three/rapier event handlers not firing for the first object, and when logging the rigidbodies, I noticed that the first rigidbody created by rapier.js always has a handle of 0, instead of the unique id every other rigidbody has. This issue can be seen in this codepen: https://codepen.io/jorjordandan/pen/zYWQZvM 
(although you will have to use your browser console to see the logs)
Technically, 0 is still a unique id if it's only on the first one, but I somehow doubt this is the intended behaviour, and it does throw a loop at anyone using conditionals on the handles (such as in the @react-three/rapier library).

**Comment by LeXXik** [comment]
How can I see the console output in your codepen? It tells me I should use native console, but the one is empty.

Anyhow, the handle is an integer starting from 0, each body is assigned +1 in order they are added to the world. It is a correct behavior. What is the use-case when you need the handle, apart from event draining callbacks? The API has been changed recently, where most of the methods are expecting the actual rigidbody object, instead of a handle number.

**Comment by jorjordandan** [comment]
Yes, during draining collision events, there's a guard that checks the rigidbody exists using the handle, which is 0 for the first one. It would be easy to fix in that lib to changing it to check for undefined, but I wanted to check whether the handle being 0 is intended behaviour or not. If it is, I can just make a PR on @react-three/rapier to handle it if it is intended.

I can see the RigidBody logs in the chrome console for the codepen ( I need to expand the objects to see the handles) not sure why they might not be showing up for you! Feel free to close the issue if it's intended behaviour I guess!

**Comment by sebcrozet** [comment]
That’s rigth, the first rigid-body, or first collider, or first joint, having an handle of 0 is the expected behavior. An handle is the concatenation of a an index (starting at 0) and a generation number (starting at 0 too).
